<?xml version="1.0" encoding="ISO-8859-1"?>
    <wsdl:definitions name="SoapService"
                 targetNamespace="http://fatcat/fatcat.wsdl"
                 xmlns="http://schemas.xmlsoap.org/wsdl/"
                 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                 xmlns:tns="http://www.examples.com/wsdl/HelloService.wsdl"
                 xmlns:xsd="http://www.w3.org/2001/XMLSchema">

        <wsdl:message name="getCustomersOrdersRequest">
            <wsdl:part name="name" type="xsd:string"/>
        </wsdl:message>

        <wsdl:message name="getCustomersOrdersResponse">
            <wsdl:part name="list" type="xsd:string"/>
        </wsdl:message>

        <wsdl:portType name="Soap_PortType">
            <soap:operation name="getCustomersOrders">
                <wsdl:input message="tns:getCustomersOrdersRequest"/>
                <wsdl:output message="tns:getCustomersOrdersResponse"/>
            </soap:operation>
        </wsdl:portType>

        <wsdl:binding name="Soap_Binding" type="tns:Soap_PortType">
            <soap:binding style="rpc"
                          transport="http://schemas.xmlsoap.org/soap/http"/>
            <wsdl:operation name="getCustomersOrders">
                <soap:operation soapAction="getCustomersOrders"/>
                <wsdl:input>
                    <soap:body
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                            namespace="urn:fatcat:get-customer-orders"
                            use="encoded"/>
                </wsdl:input>

                <wsdl:output>
                    <soap:body
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                            namespace="urn:fatcat:get-customer-orders"
                            use="encoded"/>
                </wsdl:output>
            </wsdl:operation>
        </wsdl:binding>

        <wsdl:service name="Soap_Service">
            <documentation>WSDL File for SoalService</documentation>
            <port binding="tns:Soap_Binding" name="Soap_Port">
                <soap:address
                        location="http://fatcat/soap/" />
            </port>
        </wsdl:service>
    </wsdl:definitions>