<?xml version="1.0" encoding="ISO-8859-1"?>
    <definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
                 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
                 xmlns:tns="urn:arnleadservicewsdl"
                 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                 xmlns="http://schemas.xmlsoap.org/wsdl/"
                 targetNamespace="urn:soapservicewsdl">

        <types>
            <xsd:schema targetNamespace="urn:getCustomersOrderswsdl">
                <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
                <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
            </xsd:schema>
        </types>

        <message name="getCustomersOrdersRequest">
            <part name="name" type="xsd:string"/>
        </message>

        <message name="getCustomersOrdersResponse">
            <part name="return" type="xsd:string"/>
        </message>

        <portType name="getCustomersOrderswsdlPortType">
            <operation name="getCustomersOrders">
                <documentation>Soap Service</documentation>
                <input message="tns:getCustomersOrdersRequest"/>
                <output message="tns:getCustomersOrdersResponse"/>
            </operation>
        </portType>

        <binding name="getCustomersOrderswsdlBinding" type="tns:getCustomersOrderswsdlPortType">
            <soap:binding style="rpc"
                          transport="http://schemas.xmlsoap.org/soap/http/"/>
            <operation name="getCustomersOrders">
                <soap:operation soapAction="urn:soapwsdl#getCustomersOrders"/>
                <input>
                    <soap:body
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                            namespace="urn:soap:getCustomersOrderswsdl"
                            use="encoded"/>
                </input>

                <output>
                    <soap:body
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                            namespace="urn:soap:getCustomersOrderswsdl"
                            use="encoded"/>
                </output>
            </operation>
        </binding>

        <service name="getCustomersOrderswsdl">
            <documentation>WSDL File for SoapService</documentation>
            <port binding="tns:getCustomersOrders" name="getCustomersOrderswsdlPort">
                <soap:address
                        location="http://fatcat/index.php/soap/" />
            </port>
        </service>
    </definitions>